name: flutter_windows_xp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  provider: ^6.0.4
  short_uuids: ^2.0.0
  tap_canvas: ^0.9.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  tuple: ^2.0.1
  popover: ^0.2.8+2
  menu_bar: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.7+3
  dart_code_metrics: ^5.5.0
  dart_code_metrics_presets: ^1.2.0
  import_sorter: ^4.6.0

flutter_gen:
  output: lib/common/

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/apps/paint/
    - assets/apps/notepad/
    - assets/apps/minesweeper/
    - assets/apps/minesweeper/digits/
    - assets/apps/minesweeper/face/
    - assets/apps/minesweeper/field/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800

    - family: Tahoma
      fonts:
        - asset: assets/fonts/tahoma/Tahoma-Regular.ttf
          weight: 400


import_sorter:
  comments: false